#!/bin/bash
#SBATCH -J PartProdHello
#SBATCH --ntasks 40
#SBATCH --nodes 5
#SBATCH --tasks-per-node 8
#SBATCH --mem-per-cpu 2GB
#SBATCH --partition partedu
cd $SLURM_SUBMIT_DIR

mpirun -np 40 ./hello

