#!/bin/bash
#BATCH -J PartProdHello
#SBATCH --ntasks 8
#SBATCH --nodes 4
#SBATCH --tasks-per-node 2
#SBATCH --mem-per-cpu 2GB
#SBATCH --partition partedu

cd $SLURM_SUBMIT_DIR

mpirun -np 8 ./hello_node

